### PR TITLE
V3.5.1

### PR DESCRIPTION
**Pull request by ikalchev**

### CODE REVIEW

**Comment by ikalchev** [comment]
@bdraco the zeroconf thing is failing the 3.5 builds. I guess we can proceed with the release anyway? Should we then disable the 3.5 tests or at least workaround this?

**Comment by bdraco** [comment]
I think we need to bump the zeroconf version in requirements.

Checking now

**Comment by bdraco** [comment]
Pretty sure https://github.com/ikalchev/HAP-python/pull/351 will fix it

**Comment by bdraco** [comment]
@ikalchev verified https://github.com/ikalchev/HAP-python/pull/353 which has all three PRs in it solve it

**Comment by ikalchev** [comment]
Awesome work!

**Comment by bdraco** [comment]
Thanks ! 🚀

**Pull request merged**
