### PR TITLE
Fix exception caused by wrong parameter encoding to tlv.encode in camera.py

### LINKED ISSUE #242: Unable to encode TLV value for camera
When trying to create a camera I'm getting this exception:

```
[hap_server] Exception in set_characteristics: object of type 'int' has no len()
Traceback (most recent call last):
  File "/home/homekit/camera_test/venv/lib/python3.7/site-packages/pyhap/hap_server.py", line 559, in handle_set_characteristics
    self.client_address)
  File "/home/homekit/camera_test/venv/lib/python3.7/site-packages/pyhap/accessory_driver.py", line 660, in set_characteristics
    char.client_update_value(cq[HAP_REPR_VALUE], client_addr)
  File "/home/homekit/camera_test/venv/lib/python3.7/site-packages/pyhap/characteristic.py", line 215, in client_update_value
    self.setter_callback(value)
  File "/home/homekit/camera_test/venv/lib/python3.7/site-packages/pyhap/camera.py", line 694, in set_endpoints
    to_base64=True)
  File "/home/homekit/camera_test/venv/lib/python3.7/site-packages/pyhap/tlv.py", line 27, in encode
    total_length = len(data)
```

I think I can see how this has happened in camera.py as tlv.encode is (I think) expecting to receive bytes, but it's being passed video_ssrc/audo_ssrc which are integers.

```
       video_ssrc = int.from_bytes(os.urandom(3), byteorder="big")
        audio_ssrc = int.from_bytes(os.urandom(3), byteorder="big")

<snip>
        response_tlv = tlv.encode(
            SETUP_TYPES['SESSION_ID'], session_id.bytes,
            SETUP_TYPES['STATUS'], SETUP_STATUS['SUCCESS'],
            SETUP_TYPES['ADDRESS'], res_address_tlv,
            SETUP_TYPES['VIDEO_SRTP_PARAM'], video_srtp_tlv,
            SETUP_TYPES['AUDIO_SRTP_PARAM'], audio_srtp_tlv,
            SETUP_TYPES['VIDEO_SSRC'], video_ssrc,
            SETUP_TYPES['AUDIO_SSRC'], audio_ssrc,
            to_base64=True)
```

This used to work though so I'm a bit confused about what has changed! I'm using python 3.7.5 and HAP-python==2.8.2

### PR DESCRIPTION
**Pull request by jdsnape**
Fixes #242

### CODE REVIEW

**Comment by bdraco** [comment]
```
mock_driver = <tests.conftest.MockDriver object at 0x7f4ad197be10>

    def test_setup_endpoints(mock_driver):
        """Test that the SetupEndpoint response is computed correctly"""
        set_endpoint_req = ('ARCszGzBBWNFFY2pdLRQkAaRAxoBAQACDTE5Mi4xNjguMS4xMTQDAjPFBAKs1gQ'
                            'lAhDYlmCkyTBZQfxqFS3OnxVOAw4bQZm5NuoQjyanlqWA0QEBAAUlAhAKRPSRVa'
                            'qGeNmESTIojxNiAw78WkjTLtGv0waWnLo9gQEBAA==')
    
        set_endpoint_res = ('ARCszGzBBWNFFY2pdLRQkAaRAgEAAxoBAQACDTE5Mi4xNjguMS4yMjYDAjPFBAK'
                            's1gQlAQEAAhDYlmCkyTBZQfxqFS3OnxVOAw4bQZm5NuoQjyanlqWA0QUlAQEAAh'
                            'AKRPSRVaqGeNmESTIojxNiAw78WkjTLtGv0waWnLo9gQYBAQcBAQ==')
    
        acc = camera.Camera(_OPTIONS, mock_driver, 'Camera')
        setup_endpoints = acc.get_service('CameraRTPStreamManagement')\
                             .get_characteristic('SetupEndpoints')
        setup_endpoints.client_update_value(set_endpoint_req)
    
>       assert setup_endpoints.get_value() == set_endpoint_res
E       AssertionError: assert 'ARCszGzBBWNF...uAAcEFqcpAA==' == 'ARCszGzBBWNF...9gQYBAQcBAQ=='
E         Skipping 161 identical leading characters in diff, use -v to show
E         - waWnLo9gQYBAQcBAQ==
E         + waWnLo9gQYEE+BuAAcEFqcpAA==

tests/test_camera.py:79: AssertionError
```
Looks like the test is getting further along

**Comment by bdraco** [comment]
```
diff --git a/tests/test_camera.py b/tests/test_camera.py
index f3424d7..3fec258 100644
--- a/tests/test_camera.py
+++ b/tests/test_camera.py
@@ -76,7 +76,11 @@ def test_setup_endpoints(mock_driver):
                          .get_characteristic('SetupEndpoints')
     setup_endpoints.client_update_value(set_endpoint_req)
 
-    assert setup_endpoints.get_value() == set_endpoint_res
+    end_point_value = setup_endpoints.get_value()
+
+    # We have random bytes in the endpoint so only the
+    # first 161 chars will match
+    assert end_point_value[:161] == set_endpoint_res[:161]
 
 
 def test_set_selected_stream_start_stop(mock_driver):
```
@jdsnape Something like this should fix the test

**Comment by jdsnape** [comment]
@bdraco Have updated the camera test - it all passes now:

```
===================================== test session starts ======================================
platform linux -- Python 3.7.3, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/jdsnape/HAP-python, inifile: setup.cfg
plugins: cov-2.8.1, timeout-1.3.4
collected 3 items

tests/test_camera.py ...                                                                 [100%]

====================================== 3 passed in 0.03s =======================================
```

**Comment by bdraco** [comment]
Testing passing for me as well.  I'm giving this a spin now

**Comment by bdraco** [comment]
Seems ok now

**Comment by bdraco** [comment]
@ikalchev Would you be able to do a release to resolve this later this week?  It appears we are close to having Home Assistant HomeKit Camera support land in https://github.com/home-assistant/core/pull/32527#issuecomment-621132695

**Comment by ikalchev** [comment]
Will do tomorrow, hope it’s ok!

**Comment by ikalchev** [comment]
2.8.3 is now available in pip/github.

Thank you all!
Ivan

**Pull request merged**
