### PR TITLE
Update hap_server.py

### PR DESCRIPTION
**Pull request by a3135134**

### CODE REVIEW

**Comment by bdraco** [comment]
@a3135134 This caused breakage for me, but I was able to solve it.  For additional details see https://github.com/ikalchev/HAP-python/pull/214

**Comment by sander-vd** [comment]
Can confirm this works, so also solves my issue when reconnecting wifi #221 thanks bdraco!

**Comment by bdraco** [comment]
Should be solved in 2.7.0+

**Comment by ikalchev** [comment]
Done in #216

**Pull request closed without merging**
