### PR TITLE
Fix exception on missing video fields

### PR DESCRIPTION
**Pull request by bdraco**
* Fix exception on missing video fields

Takes care of the `# TODO: Optionals, handle the case where they are missing`.  Sometimes streams would fail to start because a field would be missing in `VIDEO_TYPES['ATTRIBUTES']`.  Everything is starting consistently now with this change.

* Make logging consistent

Logging was calling `logging` instead of `logger` like the other modules.  This meant the debug log didn't show up in Home Asssistant.

### CODE REVIEW

**Comment by bdraco** [comment]
Also Home Assistant now has HomeKit camera support in the upcoming 0.110 🍾

**Comment by ikalchev** [comment]
I suppose a release with the fix is needed. Anything else I should wait for before doing it?

**Comment by bdraco** [comment]
> I suppose a release with the fix is needed. Anything else I should wait for before doing it?

Nothing else in the queue so a release would be appreciated. Thank you!

**Comment by bdraco** [comment]
Well @ikalchev, looks like I was wrong there is one more thing I found when I was adding and removing test bridges for cameras https://github.com/ikalchev/HAP-python/pull/246

Thanks again for the reviews and releases. 🎉

**Pull request merged**
