### PR TITLE
Various code cleanups, add py37/38 to travis

### PR DESCRIPTION
**Pull request by bdraco**
This is a work in progress and will conflict with https://github.com/ikalchev/HAP-python/pull/252 so I'll rework it after that

### CODE REVIEW

**Comment by bdraco** [comment]
https://travis-ci.org/github/ikalchev/HAP-python/builds/687462410

Decorator to stop the driver doesn't seem to work in py37/38

**Comment by bdraco** [comment]
Travis is clean, https://travis-ci.org/github/ikalchev/HAP-python/builds/690088291

pylint ✅ 
py37 ✅ 
py38 ✅

**Comment by bdraco** [comment]
@ikalchev 

The CI is now working for py37 and py38

If this change is acceptable along with #252, I'd like to start working on changes for Home Assistant 0.111 so a release with these would be appreciated.

**Comment by ikalchev** [comment]
So so very nice - I had just one comment.

Would you prefer this one to be merged first?

**Comment by bdraco** [comment]
> So so very nice - I had just one comment.
> 
> Would you prefer this one to be merged first?

This one depends on the test cleanup in #252 in it so #252 should merge first 👍

**Comment by ikalchev** [comment]
Merged #252 - you need any changes here?

**Comment by bdraco** [comment]
Fixing the conflict now

**Comment by bdraco** [comment]
It would be nice to fix the `Accessory.run_at_interval` that is broken in py37 and py38 but its not needed for the release

**Comment by bdraco** [comment]
CI still passing after conflict fix
https://travis-ci.org/github/ikalchev/HAP-python/builds/690162986

**Comment by bdraco** [comment]
@ikalchev Can we get a version bump?  I'd like to get #253 out in the next Home Assistant patch release.

**Comment by ikalchev** [comment]
Sure, should be able to do that tomorrow

**Comment by bdraco** [comment]
Sorry to ping again @ikalchev.   I'm getting a bit nervous about being to get everything tied up before Home Assistant 0.111 goes to beta.  I'd really appreciate it if you could find the time get a release published.

**Comment by ikalchev** [comment]
Done (v2.9.0 on tags, branch and at pip)! Sorry for the delay - hectic week.

Thanks for the good work,
Ivan

**Comment by bdraco** [comment]
Thank you.  It has been a long week for sure.  Hope you are doing well!

**Comment by ikalchev** [comment]
All good, same to you 👌🏼

**Pull request merged**
