### PR TITLE
Add bandit to CI and address reported issues

### PR DESCRIPTION
**Pull request by bdraco**
The CI Fix is in https://github.com/ikalchev/HAP-python/pull/320 which needs to go in first

This one will need to be rebased as it will conflict with the other open PRs.

### CODE REVIEW

**Comment by ikalchev** [comment]
Will release over the weekend, @bdraco

**Comment by bdraco** [comment]
> Will release over the weekend, @bdraco

Perfect, thank you!

**Comment by bdraco** [comment]
Just realized we are up to 90% on codecov 👍

**Comment by ikalchev** [comment]
It's all you mate :)

**Pull request merged**
