### PR TITLE
Setup build dir for docs

### PR DESCRIPTION
**Pull request by jslay88**

### CODE REVIEW

**Comment by jslay88** [comment]
Or merge this

**Comment by ikalchev** [comment]
Ah ok, sorry again.

**Comment by jslay88** [comment]
All good. We are both new to this process. :)

**Comment by ikalchev** [comment]
:) catching up now

**Comment by jslay88** [comment]
We will need to go through more of the project and switch over to sphinx docstrings. I only hit `Accessory`, `Bridge`, and `AccessoryDriver`.

**Pull request merged**
