### PR TITLE
Merge master back into dev

### PR DESCRIPTION
**Pull request by ikalchev**

### CODE REVIEW

**Comment by cdce8p** [comment]
The issue is, that you squash merged #110.
The best solution would be to revert the PR and merge it again with a normal merge.

**Comment by cdce8p** [comment]
Although it now looks about right.

**Comment by ikalchev** [comment]
Actually the problem was an additional space on a single line in the char tests

**Comment by ikalchev** [comment]
I guess the space was from some PR and my editor auto-removed it (since it was trailing)

**Comment by cdce8p** [comment]
In case of a normal merge, this wouldn't had been an issue for this PR which is why I suggested it. However, that works as well.

Thanks for doing the release.

**Comment by ikalchev** [comment]
And thank you for the improvements 👍

**Pull request merged**
