### PR TITLE
Service callbacks example

### PR DESCRIPTION
**Pull request by bdraco**
Docs for https://github.com/ikalchev/HAP-python/pull/229

### CODE REVIEW

**Comment by bdraco** [comment]
@ikalchev Any chance we can get a release bump before the HASS 0.108 beta?

**Comment by ikalchev** [comment]
I will release tonight (UTC+2). Hope that is not too late.

**Comment by ikalchev** [comment]
Just released 2.8.0 both in pip and here. Let me know if there are issues.

**Comment by bdraco** [comment]
TYVM!  Testing now

**Comment by bdraco** [comment]
Working great on 4 home assistant installs.

**Pull request merged**
