### PR TITLE
Add support for multiple camera streams

### PR DESCRIPTION
**Pull request by bdraco**
Setting `stream_count` to a value above 1 will create multiple `CameraRTPStreamManagement` services.

This should be backwards compatible.

### CODE REVIEW

**Comment by bdraco** [comment]
Travis is passing

https://travis-ci.org/github/ikalchev/HAP-python/builds/709566632

**Comment by bdraco** [comment]
Thanks @ikalchev.  Can we get a new release so I can get the Home Assistant changes merged?

**Comment by ikalchev** [comment]
Sure, hopefully over the weekend though

**Comment by bdraco** [comment]
> Sure, hopefully over the weekend though

Perfect. Thank you 🥇

**Comment by ikalchev** [comment]
Released as 3.0.0. Thanks!

**Pull request merged**
