### PR TITLE
Retain the original format of the UUID

### PR DESCRIPTION
**Pull request by bdraco**
apple seems to keep changing the case on these so we will now keep the binary blob and send back the exact bytes that was used in pairing when the client list pairings.

This should fix the users having trouble after migrating to the new home arch

### CODE REVIEW

**Comment by Ghawken** [comment]
Hi 
Thanks for you continued support of these libraries.

With this change here - don't we need hap_handler pair_five also updated?  
Geting an exception as pair_five is sending uuid rather than bytes to accessory_handler.pair?

**Comment by bdraco** [comment]
There is still more. Ran out of time before takeoff.  Will be infrared when finished and tested

**Comment by bdraco** [comment]
I think I got everything. At least mypy checks out.  Traveling though so can't test locally until I get back home

**Comment by Ghawken** [comment]
Thanks.  Happy travels.  Testing here no issues thus far…

**Comment by bdraco** [comment]
all seems ok, but more testing needed and I made some zeroconf changes today so I need to wait to finish testing that for 48 hours before I can validate this to make sure I know which change has which side effects.

speaking of that, this lib needs to accept multiple addresses to publish via mdns since ipv6/ipv4 dual stacks won't work otherwise which would probably make homekit work for a lot more people

**Comment by Ghawken** [comment]
Good luck.
One thing I have recently noticed is pyHAP uses 8.8.8.8 gmail/DNS to decide local ivp4 interface.   If 8.8.8.8 blocked (which many might do to prevent other DNS servers) probably would also lead to issues?

https://github.com/ikalchev/HAP-python/blob/8b62c1965b8d88d79b26d1d857408659ab9b84ba/pyhap/util.py#L48

Interesting still seems to be preferred option - although can use:
`
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        s.connect(('10.255.255.255', 80))
        addr = s.getsockname()[0]
`

Which I am testing currently….

**Comment by ikalchev** [comment]
Hey - I will go through the PRs and merge on Sunday probably (not around a computer till then)

**Comment by bdraco** [comment]
Great.  I will try to get the mdns / IPv6 stuff done before than. 

I’m still testing this one

**Comment by bdraco** [comment]
testing looks good

**Comment by bdraco** [comment]
I've been running all 4 of the open PRs on production for a few days.   Everything seems nice and snappy

**Comment by ikalchev** [comment]
@bdraco there seem to be some merge conflicts. Do you mind having a look.

Will merge and release tomorrow if you can address these - that's a promise

**Comment by bdraco** [comment]
I'll fix them in a moment

**Comment by bdraco** [comment]
@ikalchev retested on production after conflicts fixed. all good 👍 

thanks

**Comment by jimmy927** [comment]
Has this made it into main yet ?
Has anyone tested if this fixes https://github.com/home-assistant/core/issues/110540 ?

**Pull request merged**
