### PR TITLE
Make service callbacks handle multiple aids

### PR DESCRIPTION
**Pull request by bdraco**
Asking siri to turn off all the light or on all the lights sends multiple aids.  Service callbacks need to support this in order for it to work.  Sorry I missed this on the first go.

https://github.com/home-assistant/core/issues/33764

### CODE REVIEW

**Comment by bdraco** [comment]
@ikalchev I'm sorry I missed this on the first go.  I'd like to get the 2 linked issues closed out if you have a moment do due another release.

**Comment by ikalchev** [comment]
@bdraco will release tonight

**Comment by bdraco** [comment]
Thank you!

**Comment by ikalchev** [comment]
2.8.2 released with both this fixed and the zeroconf iface option

**Pull request merged**
