### PR TITLE
TV accessory

### PR DESCRIPTION
**Pull request by maximkulkin**
Adds example of TV accessory along with necessary fixes in framework.

### CODE REVIEW

**Comment by adrum** [comment]
This also fixes https://github.com/home-assistant/home-assistant/issues/25890. Thanks for tracking this down!

**Comment by ikalchev** [comment]
Good work, cheers!

Best,
Ivan

**Comment by barns102** [comment]
@maximkulkin what do I need to do to use this to fix my issue. Thanks in advance.

**Comment by barns102** [comment]
@ikalchev Are you able to help me with this?

**Comment by maximkulkin** [comment]
@barns102 I’m sorry, but I have no idea what SmartIR is and how this all related.

**Comment by barns102** [comment]
hey @maximkulkin or @ikalchev, do you know when this fix will be adopted into Home Assistant?

Thanks in Advance.

**Pull request merged**
