### PR TITLE
Fix compatibility with zeroconf 0.27

### LINKED ISSUE #262: Two exceptions raised while driver starts up
I'm running version 2.8.4 of HAP-python and version 0.27.0 of zeroconf. While trying to pair with HomeKit, as the driver starts up the following traceback is thrown:
```

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 1312, in run
    reader.handle_read(socket_)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 1379, in handle_read
    self.zc.handle_query(msg, None, _MDNS_PORT)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2676, in handle_query
    service.text,
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 623, in __init__
    assert isinstance(text, (bytes, type(None)))
AssertionError

Future exception was never retrieved
future: <Future finished exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyhap/accessory_driver.py", line 287, in _do_start
    self.advertiser.register_service(self.mdns_service_info)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2374, in register_service
    self._broadcast_service(info)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2414, in _broadcast_service
    DNSText(info.name, _TYPE_TXT, _CLASS_IN | _CLASS_UNIQUE, info.other_ttl, info.text), 0
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 623, in __init__
    assert isinstance(text, (bytes, type(None)))
AssertionError
```

### PR DESCRIPTION
**Pull request by bdraco**
Fixes #262

### CODE REVIEW

**Comment by ikalchev** [comment]
Should we also update requirements.txt to require zaeroconf >=0.27?

**Comment by elupus** [comment]
Then again, the lib doesn't do that for it's tests. So..

**Comment by bdraco** [comment]
> Should we also update requirements.txt to require zaeroconf >=0.27?

It should work with both newer and older versions due to the keyword args being added.  Sadly we are going to need another release sometime soon to unblock Home Assistant from upgrading.

**Comment by bdraco** [comment]
Verified with busy home that both 0.26.3 and 0.27.0 work with the change

**Comment by ikalchev** [comment]
Will release later today

**Comment by bdraco** [comment]
> Will release later today

Thanks.  2.9.0 has been going great, no more cpu spikes or unexpected reconnects after running it since you published.

**Comment by ikalchev** [comment]
2.9.1 is now GA

**Pull request merged**
