### PR TITLE
Fix pairing with iOS 16

### PR DESCRIPTION
**Pull request by bdraco**
UUIDs must be upper case with iOS 16 or they will get unpaired by the iOS device because it no longer compares them case insensitive.

### CODE REVIEW

**Comment by henrik-dmg** [comment]
@ikalchev could this be merged potentially? My code stopped working after the recent Home app upgrade and this should fix it

**Comment by Ghawken** [comment]
Hi
@bdraco thanks for your **considerable** work on this library - utilizing it and your latest updates in non-HA automation.

Working my way through OS16.2 changes:
With the upper case change to UUID - seeing a few : Client 22a4f0df-9148-4bf7-91ea-9550ef223a15 attempted pair verify without being paired to %s first.", from Hap_handler - _pair_verify_two.  Oddly the bridge still functions - tracking down this issue currently

Wonder whether the uppercase Client UIDD needs to be more widespread?
& working way though how to avoid need to re-pair once upgraded system to 16.2 (repair obviously a pain for users and removes room allocation etc)
Any thoughts?

**Comment by bdraco** [comment]
> Wonder whether the uppercase Client UIDD needs to be more widespread?
> & working way though how to avoid need to re-pair once upgraded system to 16.2 (repair obviously a pain for users and removes room allocation etc)
> Any thoughts?

`_handle_list_pairings` is the only place we reflect the UUID back to the client so it doesn't really matter how we store them internally.

**Comment by Ghawken** [comment]
Ok.  Thanks.
I presume that would mean that no way to migrate clients from <16.2 to new 16.2 architecture without a re-pair and a subsequent upper UUID expected by clients?

**Comment by bdraco** [comment]
You shouldn't have to do anything besides install this PR. No repair needed

**Comment by Ghawken** [comment]
Ok.  
Something else is up - will have to upgrade when my devices support soon enough to sort out.
Thanks again.

**Comment by ikalchev** [comment]
Sorry for the delay on this. Let me go over other pending fixes and will do a release in the next few days.

**Comment by bdraco** [comment]
> Sorry for the delay on this. Let me go over other pending fixes and will do a release in the next few days.

Thanks!

**Comment by Pythonaire** [comment]
I face the same error, but it is just related to older iOS 15.X clients.

**Comment by Pythonaire** [comment]
> I face the same error, but it is just related to older iOS 15.X clients.

for inspecting: 

I have two bridges. One under Ubuntu with Hap-Python version 4.5 and second under raspberian bullseye Hap-Python version 4.4 (4.5 couldn't be installed under raspberian). 
Under raspberian and 4.4, i didn't see these errors. Under Ubuntu and 4.5 i do. 

To check a version problem, i step down the Hap-Python version to 4.4 on Ubuntu. Nothing changed.

**Comment by gpala7077** [comment]
Will this be implemented in a new release?

**Comment by skarol** [comment]
@ikalchev any update on which release we can expect the fix?

**Comment by ikalchev** [comment]
@skarol Done!

**Comment by Pythonaire** [comment]
Unfortunately, Version 4.5 and 4.6 can‘t be upgraded on Raspberry ( bullseye, Pi 4, Python 3.9)

**Comment by bdraco** [comment]
If you don't have a working rust compiler you'll need to ask pyca to add wheels for your platform

**Comment by Pythonaire** [comment]
> If you don't have a working rust compiler you'll need to ask pyca to add wheels for your platform

Thx. I'm  not familiar with it. pyca means "Opencast Capturing Agent"?

**Comment by bdraco** [comment]
https://github.com/pyca

**Comment by Pythonaire** [comment]
Strange, but work.
1) uninstall Hap-python 4.4
2) uninstall cryptography
3) clear wheel cache 
4) reinstall rust
5) install cryptography needs around 10 minutes

**Comment by HVR88** [comment]
Is this fix included in HA 2022.12.3?

This integration no longer works with iOS/tvOS/HomePod updated to 16.2 and Homekit's new architecture.

Entities can be added to Homekit, but are immediately unresponsive/unavailable "No Response" in Home app.

Testing on a new Home - Every Homekit hub has been fully reset (factory reset) and Homekit completely restarted from scratch.

**Comment by TonySeedy** [comment]
I have to override Homekit by using **custom_components**

For those who can't upgrade to the new Home Assistant and want to fix this issue

Download your currently Home Assistant (https://github.com/home-assistant/core/releases)

go to **/components** and copy folder **homekit**
In **homekit** folder you have to edit file: **manifest.json**

In "**requirements**" section:
Change "_HAP-python==4.5.0_" (maybe different, depend on your HA version) to "_ha-HAP-python==4.5.2_"
(this **ha-HAP-python==4.5.2** version will fix pair with iOS 16 as [bdraco](https://github.com/bdraco) wrote)

add "version":"1.0.0" to the end of file manifest.json (require)

compress **homekit** folder and upload to **custom_components**
unzip **homekit** and restart Home Assistant

In my case, I have to delete Homekit in add integrations again (it will automatically download dependencies)

Warning: You have to delete all device in Homekit (except device not from HA) and setup it again, you can use **Controller for Homekit** to backup device and scenes, automations,....

Hope this help someone

**Comment by bdraco** [comment]
> For those who can't upgrade to the new Home Assistant and want to fix this issue

Why can't you upgrade to a new version of HA?

**Comment by TonySeedy** [comment]
> > For those who can't upgrade to the new Home Assistant and want to fix this issue
> 
> Why can't you upgrade to a new version of HA?

I am using smart home of a company in my country, the Home hub use Home Assistant to control all device they made
They use HA version is 2022.07.03
I can't upgrade, I don't have root privileges and if I upgrade by myself, it might not work anymore

**Comment by bdraco** [comment]
> I am using smart home of a company in my country, the Home hub use Home Assistant to control all device they made
> They use HA version is 2022.07.03

Do you have a link you can share with more information?

**Comment by TonySeedy** [comment]
> Do you have a link you can share with more information?

They made a device, called a home hub (or home center), to manage smart devices
You can see the device here: [Image](https://javishome.vn/storage/photos/shares/drivce_photo_dao/Bo_trung_tam/delux/nh_b__a.jpg)

Home hub using Home Assistant software and support zigbee
The company name JavisHome (not support english)

**Pull request merged**
