### PR TITLE
Add support for Write Responses

### PR DESCRIPTION
**Pull request by kormax**
This PR adds preliminary support for "wr" (Write Response) functionality, where a 'r': True In characteristic update payload indicates a request for 'value' field in response data. You can observe such requests if you run demo code provided by me [in previous PR](https://github.com/ikalchev/HAP-python/pull/454) with DEBUG logging level ON.

This feature is heavily used for Home Key lock configuration, with most commands sent to "[NFCAccessControlPoint (Link to examples)](https://github.com/kupa22/apple-homekey?tab=readme-ov-file#characteristic-nfc-access-control-point)"  expecting to get a special response this way. Without it, the user device will re-try same commands a couple of times, indicating a lack of expected response. (With this commit, behaviour is as expected in a WIP demo app).

Considering my lack of experience with HAP and this library's codebase in particular, I am unable to verify that proposed changes don't break compatibility with existing code (apart from some testing done locally), with an expert's look needed for that. IMO.
My intention was to make as little changes as possible, but IMO `set_characteristics` method could also be refactored to better support this feature in the future. Didn't want to do that due to beforementioned reasons.

### CODE REVIEW

**Comment by ikalchev** [comment]
Thanks for the change!

@bdraco can you have a look as well? Looks good to me apart from some needed refactoring at a later stage (not this PR)

**Comment by bdraco** [comment]
Looks ok to me besides this function is too complex and needs to be refactored.  It was already too complex before and this is making it a bit worse.  That can be done in a future PR.

I will test this one production now

**Comment by bdraco** [comment]
Looks ok to me besides this function is too complex and needs to be refactored.  It was already too complex before and this is making it a bit worse.  That can be done in a future PR.

I will test this one production now

**Comment by bdraco** [comment]
Tested on production. No breakage observed (sorry for the multi-posts, I'm on a plane and the wifi is bad)

**Comment by bdraco** [comment]
Tested on production. No breakage observed (sorry for the multi-posts, I'm on a plane and the wifi is bad)

**Comment by bdraco** [comment]
Tested on production. No breakage observed (sorry for the multi-posts, I'm on a plane and the wifi is bad)

**Comment by kormax** [comment]
I think that the only behavior change that could affect legacy code is  that if someone returned a non-None value from setter callback, it would start sending that data as a "value" field in write response. But from what I understand, device should just ignore unknown fields, so that shouldn't be a problem.

**Pull request merged**
