### PR TITLE
Sphinx Documentation

### PR DESCRIPTION
**Pull request by jslay88**
For Issue #46

### CODE REVIEW

**Comment by jslay88** [comment]
Generally, you dont put the build dir on the repo.

**Comment by ikalchev** [comment]
I am unaware, I was just looking at this: https://github.com/home-assistant/home-assistant/tree/dev/docs/build

But if you say things are fine as is, I am ready to merge.

**Comment by jslay88** [comment]
It can make for less confusion to have it. I'll add it in since it effectively doesn't harm anything.

**Comment by jslay88** [comment]
Probably best for you to do it at this point, but remove `build` from `.gitignore` and add the .empty

**Comment by ikalchev** [comment]
Sorry, I saw you removed the build from gitignore.

**Pull request merged**
