### PR TITLE
Handle a single byte read request in encrypted data stream

### LINKED ISSUE #230: AssertionErrors referencing macOS machine
When using the Home Assistant [Homekit integration](https://www.home-assistant.io/integrations/homekit/), I occasionally get backtraces referencing HAP-python:
```
----------------------------------------
Exception happened during processing of request from ('192.168.2.2', 64896)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 880, in finish_request
    self, self.accessory_handler)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 151, in __init__
    super(HAPServerHandler, self).__init__(sock, client_addr, server)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 394, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 702, in recv_into
    data = self.recv(nbytes, flags)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 725, in recv
    block_length_bytes = self.socket.recv(self.LENGTH_LENGTH)
  File "/srv/homeassistant-3.7/lib/python3.7/site-packages/pyhap/hap_server.py", line 713, in recv
    assert not flags and buflen > self.LENGTH_LENGTH
AssertionError
----------------------------------------
```
In the backtrace above, the 192.168.2.2 host is an unrelated macOS host running 10.15.3. That host has Homekit configured via the Home app but otherwise doesn't provide any Homekit services.

### PR DESCRIPTION
**Pull request by bdraco**
Fixes #230

Leaving this as a draft as I want to run it for a few days.

### CODE REVIEW

**Comment by bdraco** [comment]
I’ve been running this for a while without any issues. It should fix the linked issue

**Comment by bdraco** [comment]
Repushing to fix `pyhap/hap_server.py:709:0: C0303: Trailing whitespace (trailing-whitespace)` (no functional changes)

**Comment by bdraco** [comment]
Travis is clean https://travis-ci.org/github/ikalchev/HAP-python/builds/702357372

**Comment by bdraco** [comment]
Thanks @ikalchev 

@jjlawren Is this causing any visible issues for you?  I expect all accessories go unavailable for a few seconds when this happens.

**Comment by jjlawren** [comment]
The original problem? So far I've only noticed the exceptions after the fact so I haven't correlated them to any Homekit behavior issues.

**Comment by bdraco** [comment]
Probably no reason to go out of the way to make a new release in that case.

**Pull request merged**
