### PR TITLE
Protocol 1.1: Upgrade protocol version (HAP-python 4.0.0)

### PR DESCRIPTION
**Pull request by bdraco**
TODO:

- [x] Implement timed writes https://github.com/ikalchev/HAP-python/pull/366

### CODE REVIEW

**Comment by bdraco** [comment]
Looks like we are almost there but we have to implement the `/prepare` endpoint

**Comment by ikalchev** [comment]
Will wait for a final nod from you before merging this and releasing

**Comment by ikalchev** [comment]
Also I think some tests fail, mind if you take look if you do any final touches here?

**Comment by bdraco** [comment]
On it

**Comment by ikalchev** [comment]
Thanks! I suspect sloppy merging on my part, so apologies.

**Comment by bdraco** [comment]
One of the PRs changed the behavior of the other.

All fixed in

https://github.com/ikalchev/HAP-python/pull/369

**Comment by bdraco** [comment]
Ideally what is merged now can be released as 3.5.3 or 3.6.0 and then merge this and release at 4.0.0 so we can do a bump in Home Assistant for 3.x and then in next month 4.x

**Comment by bdraco** [comment]
rebased to make sure this is clean against dev

**Pull request merged**
