### PR TITLE
add support for television

### LINKED ISSUE #185: New Accessory Typs + Services
It seems their might have been new accessories added with iOS version 12.2 beta 1.
I recently saw a feature request to add a TV service and found this afterwards:
https://github.com/KhaosT/HAP-NodeJS/pull/638

I tried to download the current HAP specifications, but it seems they aren't available at the moment. At least I always get an error message. Maybe (Hopefully) they are being updated now.

### PR DESCRIPTION
**Pull request by adrum**
Manually copied values from https://github.com/KhaosT/HAP-NodeJS/pull/638

Fixes #185

### CODE REVIEW

**Comment by adrum** [comment]
I have this functional in HomeAssistant in [this branch](https://github.com/adrum/home-assistant/tree/add-homekit-television?files=1). I'll submit a PR there once this has been merged and a new version has been released.

**Comment by cdce8p** [comment]
Hi, awesome that you've put in the work to manually copy the chars and services :+1: 
I haven't had the time to look at you're changes in detail yet.

Some things that might help you:
- If a char has `uint8` as its format, it will only look at the corresponding `valid_values`. `Min` and `max` are in therefore redundant.
- I saw you've added the distinction between `primary` and `linked` services. If I recall correctly, and I hope I do (it has been a while), the `HAP` protocol automatically interprets the first added service as the `primary` one. All others are automatically the `linked` ones.

**Comment by ikalchev** [comment]
Hey, so great that you made this change! Let me know when it is ready to merge it. I think I will do a pip release with the merge as well.

Best,
Ivan

**Comment by adrum** [comment]
@cdce8p I've removed the redundant min/max values where all the valid values were filled out. I wasn't sure what to do with ones like `RemoteKey` since there were some missing. This is how it is in the HAP-NodeJS project as well. 

When I was testing my HomeAssistant branch with my changes for this library, my Input Sources weren't properly showing to be associated with the television until I added the ability to set the services as linked in the `to_HAP` function. I wasn't too sure about the primary service part of it, so I went ahead and added it just in case.

**Comment by adrum** [comment]
@cdce8p I just tested removing the `add_linked_service` and `is_primary_service` and the source inputs would not show up as services on the tv services. Based on my testing, these seem to be required for the `Television` service to work properly.

**Comment by ikalchev** [comment]
@adrum I am Ok to merge this if you are ready.

**Comment by adrum** [comment]
@ikalchev I think this is ready to go.

**Comment by adrum** [comment]
@ikalchev Can you make a release with this? I think I've got the HomeAssistant PR ready to go.

**Comment by ikalchev** [comment]
Released under 2.5.0 in pypi, added GitHub release as well.

**Pull request merged**
